# ─────────────────────────────────────────────────────────────
# Per-host settings, keyed by hostname.
#
# The active host is chosen by the file /etc/nixos/hostname
# (gitignored, one line: "z3-nix01", "node2", …). configuration.nix
# reads that name, looks up `hosts.<name>` and merges it with the
# cluster-wide keys below, exposing the result to every module as
# the `settings` argument (via `_module.args.settings`).
#
# To add a host: copy a node entry, change its values, then create
# /etc/nixos/hostname on that machine. Nothing else in the repo
# needs editing (except re-encrypting secrets for the new host's
# age key — see README).
#
# Hardware layouts are committed per host too: `local/<hostname>-hardware-configuration.nix`
# (e.g. local/z3-nix01-hardware-configuration.nix), generated by nixos-generate-config
# on each host and imported by configuration.nix. No per-host files conflict in git.
# ─────────────────────────────────────────────────────────────
{
  # ── Per-host settings ───────────────────────────────────────
  hosts = {
    z3-nix01 = {
      hostId = "01234567";          # ZFS hostid — MUST be unique per host!
      localAddress = "172.16.3.4";  # this host's underlay IP
      nodeIndex = 0;                # index into centralNodes (z3-nix01=0, node2=1, node3=2)
      uplinkInterface = "ens18";    # NIC this host's uplink was detected as
      timeZone = "Europe/London";
    };

    node2 = {
      hostId = "00000000";          # TODO: generate a unique hostid (e.g. `genhostid`)
      localAddress = "172.16.3.5";
      nodeIndex = 1;
      uplinkInterface = "ens18";
      timeZone = "Europe/London";
    };

    node3 = {
      hostId = "00000000";          # TODO: generate a unique hostid (e.g. `genhostid`)
      localAddress = "172.16.3.6";
      nodeIndex = 2;
      uplinkInterface = "ens18";
      timeZone = "Europe/London";
    };

    # Add node4, … here when needed.
  };

  # ── Cluster-wide (SAME on every host) ───────────────────────
  centralNodes = [ "172.16.3.4" "172.16.3.5" "172.16.3.6" ];  # z3-nix01 node2 node3
  cephNodes = [ "172.16.3.4" "172.16.3.5" "172.16.3.6" ];    # Ceph mon IPs (z3-nix01 node2 node3) — one mon per node
  dnsZone = "incus-cluster1.mydomain";                        # fabric DNS zone
  cephFsid = "ede5176c-2777-4e6d-9cf1-529d4dfe0057";          # Ceph cluster FSID
}
